### ISSUE TITLE
link to zine thread is broken

### ISSUE THREAD

**Issue by n8fr8** [DevSqNet/devsqnet.github.io#3]
https://talk.developersquare.net/t/follow-this-thread-for-devsq-zine-updates/ no longer exists

**Comment by noneck** [comment]
interesting. in my other instance, archive URLs point back to their original posting. < https://talk.developersquare.net/t/download-the-devsq-zine/154 >

how do you feel about having a monthly call for articles, etc?

**Comment by n8fr8** [comment]
Sure!

**Comment by noneck** [comment]
@n8fr8 I've updated the link. Please push this to the local box. 
< https://github.com/DevSqNet/devsqnet.github.io/pull/4 >

I'll start a new thread and start asking for feedback.

**Comment by n8fr8** [comment]
website has been updated

**Comment by noneck** [comment]
Confirmed.
